"""
Extract rows for each of the 6 first-diagnosis tasks,
formatted for querying off-the-shelf LLMs.

Tasks: new_hypertension, new_hyperlipidemia, new_pancan, new_celiac, new_lupus, new_acutemi

Logic mirrors FirstDiagnosisTimeHorizonCodeLabeler in ehrshot/labelers/ehrshot.py:
  - prediction_time = 11:59 PM on day of DISCHARGE from inpatient visit
  - history = all events in ehrshot.csv with start < prediction_time
  - label = True if patient receives this diagnosis FOR THE FIRST TIME within 1-365 days
  - patients who already have the diagnosis are excluded (already handled in labeled_patients.csv)

A patient can appear multiple times (once per valid inpatient discharge before their first
diagnosis). Use --prediction_strategy to control how many rows per patient to keep:
  first  — earliest discharge only (most history available for negative cases)
  last   — latest discharge only (closest to potential diagnosis, most informative)
  all    — every discharge (matches the original benchmark's full label set)

Verification against notebook stats (all patients, not split):
  new_hypertension:  3764 labels,  2328 patients, prevalence ~13.7%
  new_hyperlipidemia: 4442 labels, 2650 patients, prevalence ~12.7%
  new_pancan:        7011 labels,  3864 patients, prevalence ~3.8%
  new_celiac:        7129 labels,  3899 patients, prevalence ~1.3%
  new_lupus:         7038 labels,  3864 patients, prevalence ~2.2%
  new_acutemi:       6837 labels,  3834 patients, prevalence ~6.8%
"""

import argparse
import os
import multiprocessing as mp
import pandas as pd
from jinja2 import Template
from tqdm import tqdm


TASK_2_DISEASE_NAME = {
    "new_hypertension":   "hypertension",
    "new_hyperlipidemia": "hyperlipidemia",
    "new_pancan":         "pancreatic cancer",
    "new_celiac":         "celiac disease",
    "new_lupus":          "systemic lupus erythematosus",
    "new_acutemi":        "acute myocardial infarction",
}

# Expected stats from the EHRSHOT paper notebook (for sanity checks)
TASK_2_EXPECTED_STATS = {
    "new_hypertension":  {"n_labels": 3764,  "n_patients": 2328, "prevalence": 0.137},
    "new_hyperlipidemia": {"n_labels": 4442, "n_patients": 2650, "prevalence": 0.127},
    "new_pancan":        {"n_labels": 7011,  "n_patients": 3864, "prevalence": 0.038},
    "new_celiac":        {"n_labels": 7129,  "n_patients": 3899, "prevalence": 0.013},
    "new_lupus":         {"n_labels": 7038,  "n_patients": 3864, "prevalence": 0.022},
    "new_acutemi":       {"n_labels": 6837,  "n_patients": 3834, "prevalence": 0.068},
}

# ------------------------------------------------------------------ #
# Module-level globals — set in the main process before Pool creation.
# On Linux (fork), child processes inherit these via copy-on-write
# without pickling, making large objects (grouped EHR, code dict) free.
# ------------------------------------------------------------------ #
_ehr_by_patient: dict = {}       # patient_id -> DataFrame of that patient's events
_code_descriptions: dict = {}    # OMOP code -> human-readable name
_max_events: int = 200

PROMPT_TEMPLATE = Template("""\
You are a clinical prediction assistant.

The following is a patient's complete medical history up to {{ date }} \
(end of their hospital discharge day). Each line is one clinical event.

--- PATIENT HISTORY ---
{{ event_history }}
--- END OF HISTORY ---

Question: Based on this history, will this patient be diagnosed with \
{{ disease_name }} for the FIRST TIME within the next 1 to 365 days after {{ date }}?

Answer:""")


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--path_to_data_csv",
                        default="./EHRSHOT_ASSETS/data/ehrshot.csv")
    parser.add_argument("--path_to_labels_dir",
                        default="./EHRSHOT_ASSETS/benchmark")
    parser.add_argument("--path_to_splits_csv",
                        default="./EHRSHOT_ASSETS/splits/person_id_map.csv")
    parser.add_argument("--path_to_concept_csv",
                        default="./EHRSHOT_ASSETS/femr/logs/omop_dir/concept.csv",
                        help="Path to concept.csv generated by Script 1 (maps codes to text descriptions).")
    parser.add_argument("--path_to_output_dir",
                        default="./llm_inputs/first_diagnosis")
    parser.add_argument("--tasks", nargs="+",
                        default=list(TASK_2_DISEASE_NAME.keys()),
                        choices=list(TASK_2_DISEASE_NAME.keys()),
                        help="Which tasks to extract. Defaults to all 6.")
    parser.add_argument("--max_events_per_patient", type=int, default=200,
                        help="Truncate to most recent N events before prediction_time.")
    parser.add_argument("--prediction_strategy", type=str, default="all",
                        choices=["first", "last", "all"],
                        help=(
                            "How to handle patients with multiple discharges:\n"
                            "  first — keep only the earliest discharge per patient\n"
                            "  last  — keep only the latest discharge per patient\n"
                            "  all   — keep all discharges (matches original benchmark)"
                        ))
    parser.add_argument("--num_workers", type=int, default=4,
                        help="Number of parallel worker processes. Defaults to all CPUs.")
    return parser.parse_args()


def load_code_descriptions(path_to_concept_csv: str) -> dict:
    """Load code -> concept_name mapping from concept.csv generated by Script 1.
    Key is '{vocabulary_id}/{concept_code}', matching the format in ehrshot.csv.
    Codes not found in Athena (e.g. CPT4) will be absent from this dict.
    """
    df = pd.read_csv(path_to_concept_csv, low_memory=False,
                     usecols=["concept_name", "vocabulary_id", "concept_code"])
    df["code"] = df["vocabulary_id"].astype(str) + "/" + df["concept_code"].astype(str)
    # Drop rows where concept_name is just the code itself (fallback entries with no real description)
    df = df[df["concept_name"] != df["code"]]
    return dict(zip(df["code"], df["concept_name"]))


def format_event_history(df_events: pd.DataFrame) -> str:
    """Convert event rows (filtered + sorted chronologically) into a plain-text timeline."""
    lines = []
    for _, row in df_events.iterrows():
        time_str = str(row["start"])[:16]   # YYYY-MM-DD HH:MM
        code      = str(row["code"])       if pd.notna(row["code"])       else "UNKNOWN"
        value     = str(row["value"])      if pd.notna(row["value"])      else ""
        unit      = str(row["unit"])       if pd.notna(row["unit"])       else ""
        table     = str(row["omop_table"]) if pd.notna(row["omop_table"]) else ""

        description = _code_descriptions.get(code)
        label = f"{description} [{code}]" if description and description != code else code
        parts = [f"[{time_str}]", label, f"(table={table})"]
        if value:
            parts.append(f"value={value}")
        if unit:
            parts.append(f"unit={unit}")
        lines.append(" | ".join(parts))
    return "\n".join(lines)


def build_prompt(disease_name: str, prediction_time: pd.Timestamp,
                 event_history: str) -> str:
    """Build a prompt for zero-shot scoring via next-token log-probabilities.

    The prompt ends at "Answer:" so that at inference time you can read off
    P("YES" | context) and P("NO" | context) directly from the next-token
    distribution — no need to construct two separate strings.
    """
    return PROMPT_TEMPLATE.render(
        date=str(prediction_time)[:10],  # YYYY-MM-DD
        disease_name=disease_name,
        event_history=event_history,
    )


def process_row(args: tuple) -> dict:
    """Worker function: extract history and build prompt for one (patient, prediction_time) row.
    Reads from module-level globals inherited via fork — no data is passed through the args tuple.
    """
    pid, pred_time, label, split, task, disease_name = args

    df_patient = _ehr_by_patient.get(pid, pd.DataFrame())
    if not df_patient.empty:
        df_patient = df_patient[df_patient["start"] < pred_time].sort_values("start")
        if _max_events and len(df_patient) > _max_events:
            df_patient = df_patient.tail(_max_events)

    history_text = format_event_history(df_patient)
    prompt       = build_prompt(disease_name, pred_time, history_text)

    return {
        "patient_id":          pid,
        "task":                task,
        "split":               split,
        "prediction_time":     pred_time,
        "label":               label,
        "n_events_in_history": len(df_patient),
        "event_history":       history_text,
        "prompt":              prompt,
    }


def verify_label_stats(df_labels: pd.DataFrame, task: str):
    """Print stats and assert they match expected values from the EHRSHOT paper."""
    expected   = TASK_2_EXPECTED_STATS[task]
    n_labels   = len(df_labels)
    n_patients = df_labels["patient_id"].nunique()
    prevalence = df_labels["value"].mean()

    print(f"  Labels:     {n_labels}  (expected {expected['n_labels']})")
    print(f"  Patients:   {n_patients}  (expected {expected['n_patients']})")
    print(f"  Prevalence: {prevalence:.4f}  (expected ~{expected['prevalence']:.3f})")

    if abs(n_labels - expected["n_labels"]) > 5:
        print(f"  WARNING: label count {n_labels} differs from expected {expected['n_labels']}")
    if abs(n_patients - expected["n_patients"]) > 5:
        print(f"  WARNING: patient count {n_patients} differs from expected {expected['n_patients']}")
    if abs(prevalence - expected["prevalence"]) > 0.01:
        print(f"  WARNING: prevalence {prevalence:.4f} differs from expected {expected['prevalence']:.3f}")

    non_2359 = df_labels[~df_labels["prediction_time"].dt.strftime("%H:%M").eq("23:59")]
    if len(non_2359) > 0:
        print(f"  WARNING: {len(non_2359)} rows not at 23:59 — unexpected.")
    else:
        print(f"  OK: all prediction times are at 23:59 as expected.")


if __name__ == "__main__":
    args = parse_args()
    os.makedirs(args.path_to_output_dir, exist_ok=True)

    # ------------------------------------------------------------------ #
    # Load shared data into module-level globals BEFORE spawning workers.
    # On Linux (fork), child processes inherit this memory via copy-on-write.
    # ------------------------------------------------------------------ #
    print("Loading splits...")
    df_splits = pd.read_csv(args.path_to_splits_csv)
    df_splits = df_splits.rename(columns={"omop_person_id": "patient_id"})

    print("Loading code descriptions from concept.csv...")
    _code_descriptions.update(load_code_descriptions(args.path_to_concept_csv))
    print(f"  Loaded {len(_code_descriptions):,} code descriptions.")

    print("Loading ehrshot.csv (this may take a moment)...")
    df_ehr = pd.read_csv(args.path_to_data_csv, low_memory=False)
    df_ehr["start"] = pd.to_datetime(df_ehr["start"])
    print(f"  Loaded {len(df_ehr):,} events for {df_ehr['patient_id'].nunique():,} patients.")

    print("Pre-grouping events by patient_id...")
    _ehr_by_patient.update({
        pid: group.reset_index(drop=True)
        for pid, group in df_ehr.groupby("patient_id")
    })
    del df_ehr  # free the full dataframe — workers only need the grouped dict
    print(f"  Grouped {len(_ehr_by_patient):,} patients.\n")

    _max_events = args.max_events_per_patient

    # ------------------------------------------------------------------ #
    # Process each task
    # ------------------------------------------------------------------ #
    for task in args.tasks:
        disease_name = TASK_2_DISEASE_NAME[task]
        print(f"{'='*60}")
        print(f"Task: {task}  ({disease_name})")

        # 1. Load labels
        path_to_labels = os.path.join(args.path_to_labels_dir, task, "labeled_patients.csv")
        df_labels = pd.read_csv(path_to_labels)
        df_labels["prediction_time"] = pd.to_datetime(df_labels["prediction_time"])

        # 2. Verify stats match the original repo
        verify_label_stats(df_labels, task)

        # 3. Apply prediction strategy
        df_labels_sorted = df_labels.sort_values(["patient_id", "prediction_time"])
        if args.prediction_strategy == "first":
            df_rows = df_labels_sorted.groupby("patient_id", as_index=False).first()
        elif args.prediction_strategy == "last":
            df_rows = df_labels_sorted.groupby("patient_id", as_index=False).last()
        else:  # all
            df_rows = df_labels_sorted

        print(f"\n  After applying strategy='{args.prediction_strategy}':")
        print(f"  Rows: {len(df_rows)},  Positive rate: {df_rows['value'].mean():.4f}")

        # 4. Attach split labels
        df_rows = df_rows.merge(df_splits, on="patient_id", how="left")
        print(f"  Split breakdown:\n{df_rows['split'].value_counts().to_string()}")

        # 5. Build worker args — only small scalar values are passed per row;
        #    large data (EHR events, code descriptions) is read from globals.
        worker_args = [
            (row.patient_id, row.prediction_time, row.value, row.split, task, disease_name)
            for row in df_rows.itertuples(index=False)
        ]

        # 6. Run in parallel
        print(f"\n  Extracting histories with {args.num_workers} workers...")
        with mp.Pool(processes=args.num_workers) as pool:
            records = list(tqdm(
                pool.imap(process_row, worker_args, chunksize=32),
                total=len(worker_args),
            ))

        # 7. Save per-task output
        df_out = pd.DataFrame(records)
        path_to_output = os.path.join(args.path_to_output_dir, f"{task}_{args.prediction_strategy}.csv")
        df_out.to_csv(path_to_output, index=False)
        print(f"\n  Saved {len(df_out)} rows -> {path_to_output}")
        print(f"  Label distribution:\n{df_out.groupby(['split','label']).size().to_string()}\n")

    print("Done.")
