"""
Extract per-event rows for training a medical-event embedding model.

For each disease task, positive and negative records are sampled independently:
  - Loop over all records of the same class (positive or negative)
  - For each (patient, prediction_time) record, sample events with probability p
  - Because of stochasticity, each pass yields different events
  - Repeat passes until total_event_target events are collected for that class
  - Then do the same for the other class

This gives balanced (or controlled) per-class event counts while naturally
augmenting via the randomness in sample_prob.

Output schema (one row per sampled event):
  patient_id          - patient identifier
  task                - task name (e.g. new_hypertension)
  split               - train / val / test
  prediction_time     - 23:59 on discharge day
  label               - 1/0 (True if first diagnosis within 1-365 days)
  pass_idx            - which sampling pass produced this event (0-based)
  event_pos           - 0-based index of this event in the *full* history up to
                        prediction_time (chronological order, before any sampling)
  history_len         - total events before prediction_time (before sampling)
  code                - OMOP code string (vocabulary_id/concept_code)
  description         - human-readable concept name (empty string if not found)
  value               - numeric or string value (NaN if absent)
  unit                - unit string (empty string if absent)
  start               - event timestamp

Tasks: new_hypertension, new_hyperlipidemia, new_pancan, new_celiac,
       new_lupus, new_acutemi

Prediction logic mirrors FirstDiagnosisTimeHorizonCodeLabeler:
  - prediction_time = 11:59 PM on day of DISCHARGE from inpatient visit
  - history = all events with start < prediction_time
  - label = True if patient receives this diagnosis for the first time
             within 1-365 days of prediction_time
"""

import argparse
import gc
import os
import multiprocessing as mp
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import time

from tqdm import tqdm


TASK_2_DISEASE_NAME = {
    "new_hypertension":   "hypertension",
    "new_hyperlipidemia": "hyperlipidemia",
    "new_pancan":         "pancreatic cancer",
    "new_celiac":         "celiac disease",
    "new_lupus":          "systemic lupus erythematosus",
    "new_acutemi":        "acute myocardial infarction",
}

# Expected stats from the EHRSHOT paper notebook (for sanity checks)
TASK_2_EXPECTED_STATS = {
    "new_hypertension":  {"n_labels": 3764,  "n_patients": 2328, "prevalence": 0.137},
    "new_hyperlipidemia": {"n_labels": 4442, "n_patients": 2650, "prevalence": 0.127},
    "new_pancan":        {"n_labels": 7011,  "n_patients": 3864, "prevalence": 0.038},
    "new_celiac":        {"n_labels": 7129,  "n_patients": 3899, "prevalence": 0.013},
    "new_lupus":         {"n_labels": 7038,  "n_patients": 3864, "prevalence": 0.022},
    "new_acutemi":       {"n_labels": 6837,  "n_patients": 3834, "prevalence": 0.068},
}

# ------------------------------------------------------------------ #
# Module-level globals — set in the main process before Pool creation.
# On Linux (fork), child processes inherit these via copy-on-write
# without pickling, making large objects (grouped EHR, code dict) free.
# ------------------------------------------------------------------ #
_ehr_by_patient: dict = {}       # patient_id -> DataFrame of that patient's events
_code_descriptions: dict = {}    # OMOP code -> human-readable name
_sample_prob: float = None       # p: per-event inclusion probability
_sample_target: int = None       # m: per-patient cap per pass (optional)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--path_to_data_csv",
                        default="./EHRSHOT_ASSETS/data/ehrshot.csv")
    parser.add_argument("--path_to_labels_dir",
                        default="./EHRSHOT_ASSETS/benchmark")
    parser.add_argument("--path_to_splits_csv",
                        default="./EHRSHOT_ASSETS/splits/person_id_map.csv")
    parser.add_argument("--path_to_concept_csv",
                        default="./EHRSHOT_ASSETS/femr/logs/omop_dir/concept.csv",
                        help="Path to concept.csv generated by Script 1.")
    parser.add_argument("--path_to_output_dir",
                        default="./data/embedding_inputs/new_diagnosis")
    parser.add_argument("--tasks", nargs="+",
                        default=list(TASK_2_DISEASE_NAME.keys()),
                        choices=list(TASK_2_DISEASE_NAME.keys()),
                        help="Which tasks to extract. Defaults to all 6.")
    parser.add_argument("--prediction_strategy", type=str, default="all",
                        choices=["first", "last", "all"],
                        help=(
                            "How to handle patients with multiple discharges:\n"
                            "  first — keep only the earliest discharge per patient\n"
                            "  last  — keep only the latest discharge per patient\n"
                            "  all   — keep all discharges (matches original benchmark)"
                        ))
    parser.add_argument("--max_rows", type=int, default=None,
                        help="Cap total (patient, prediction_time) rows per task (for debugging).")
    parser.add_argument("--num_workers", type=int, default=4,
                        help="Number of parallel worker processes.")
    parser.add_argument("--event_sample_prob", type=float, default=None,
                        help="Probability p of including each event per pass.")
    parser.add_argument("--event_sample_target", type=int, default=None,
                        help="Per-patient cap: stop sampling after m events per patient per pass.")
    parser.add_argument("--total_event_target", type=int, default=None,
                        help=(
                            "Target number of samples per class per split (applied to all splits "
                            "unless overridden by --train_target / --val_target / --test_target). "
                            "If None and no per-split targets are set, a single pass is run."
                        ))
    parser.add_argument("--train_target", type=int, default=None,
                        help="Target samples per class for the train split (overrides --total_event_target).")
    parser.add_argument("--val_target",   type=int, default=None,
                        help="Target samples per class for the val split (overrides --total_event_target).")
    parser.add_argument("--test_target",  type=int, default=None,
                        help="Target samples per class for the test split (overrides --total_event_target).")
    return parser.parse_args()


def load_code_descriptions(path_to_concept_csv: str) -> dict:
    """Load code -> concept_name mapping from concept.csv.
    Key is '{vocabulary_id}/{concept_code}', matching the format in ehrshot.csv.
    """
    df = pd.read_csv(path_to_concept_csv, low_memory=False,
                     usecols=["concept_name", "vocabulary_id", "concept_code"])
    df["code"] = df["vocabulary_id"].astype(str) + "/" + df["concept_code"].astype(str)
    df = df[df["concept_name"] != df["code"]]
    return dict(zip(df["code"], df["concept_name"]))


def _worker_init():
    """Seed numpy's RNG uniquely per worker so stochastic sampling is independent."""
    np.random.seed((os.getpid() * 6364136223846793005 + int(time.time() * 1e6)) % (2 ** 32))


def process_row(args: tuple) -> list[dict]:
    """Worker function: extract per-event rows for one (patient, prediction_time).

    Returns a list of dicts — one per sampled event — each carrying:
      - patient/task/split/prediction_time/label context
      - event_pos: the event's 0-based index in the *full* history (before sampling)
      - history_len: length of the full history (before sampling)
      - raw event fields: code, description, value, unit, start
    Note: pass_idx is added by the caller, not here.
    """
    pid, pred_time, label, split, task = args

    df_patient = _ehr_by_patient.get(pid, pd.DataFrame())
    if df_patient.empty:
        return []

    # Full chronological history before prediction_time (positions are indices here)
    df_history = df_patient[df_patient["start"] < pred_time].sort_values("start").reset_index(drop=True)
    history_len = len(df_history)

    if history_len == 0:
        return history_len, []

    # Sample indices from most-recent to oldest, recording their original positions
    if _sample_prob is not None:
        selected_positions = []
        for i in range(history_len - 1, -1, -1):
            if np.random.random() < _sample_prob:
                selected_positions.append(i)
                if _sample_target is not None and len(selected_positions) >= _sample_target:
                    break
        selected_positions = sorted(selected_positions)  # restore chronological order
    else:
        selected_positions = list(range(history_len))

    if not selected_positions:
        return history_len, []

    df_sampled = df_history.iloc[selected_positions]

    records = []
    for pos, (_, row) in zip(selected_positions, df_sampled.iterrows()):
        code = str(row["code"]) if pd.notna(row["code"]) else "UNKNOWN"
        description = _code_descriptions.get(code, "")

        raw_val = row["value"]
        value = str(raw_val) if pd.notna(raw_val) else ""

        unit = str(row["unit"]) if pd.notna(row["unit"]) else ""

        records.append({
            "event_pos":        pos,
            "start":            row["start"],
            "code":             code,
            "description":      description,
            "value":            value,
            "unit":             unit,
        })

    return history_len, records


def collect_to_target(
    df_class_rows: pd.DataFrame,
    task: str,
    target: int,
    num_workers: int,
    label_name: str = "",
) -> list[dict]:
    """Collect exactly `target` samples in a single multiprocessing pass.

    Repeats the base worker_args list enough times to reach `target`, shuffles
    the whole expanded list, truncates to exactly `target`, then runs one Pool
    pass. Because sample_prob is stochastic, repeated entries for the same
    (patient, prediction_time) produce different event subsets.

    Each event row is tagged with:
      sample_id  — 0-based index into the expanded+shuffled list (groups events
                   within one sample)
      pass_idx   — which repetition of the base list this entry came from
    """
    base_args = [
        (row.patient_id, row.prediction_time, row.value, row.split, task)
        for row in df_class_rows.itertuples(index=False)
    ]
    n_records = len(base_args)

    # Repeat the list enough times, tag each entry with its repetition index
    # (used later as pass_idx), then shuffle and truncate to target.
    n_repeats = -(-target // n_records)  # ceil division
    tagged = [(args, rep) for rep in range(n_repeats) for args in base_args]
    np.random.shuffle(tagged)
    tagged = tagged[:target]

    worker_args = [args for args, _ in tagged]
    pass_indices = [rep  for _, rep in tagged]

    rows = []
    with mp.Pool(processes=num_workers, initializer=_worker_init) as pool:
        for sample_id, (worker_arg, (history_len, event_list)) in enumerate(zip(
            worker_args,
            tqdm(
                pool.imap(process_row, worker_args, chunksize=32),
                total=len(worker_args),
                desc=f"  [{label_name}]",
            ),
        )):
            pid, pred_time, label, split, task_ = worker_arg
            rows.append({
                "sample_id":       sample_id,
                "pass_idx":        pass_indices[sample_id],
                "patient_id":      pid,
                "task":            task_,
                "split":           split,
                "prediction_time": pred_time,
                "label":           label,
                "history_len":     history_len,
                "n_events":        len(event_list),
                "events":          event_list,
            })

    return rows


def run_single_pass(
    df_rows: pd.DataFrame,
    task: str,
    num_workers: int,
) -> tuple[list[dict], list[dict]]:
    """Single-pass extraction (no total_event_target). Mirrors original behaviour."""
    worker_args = [
        (row.patient_id, row.prediction_time, row.value, row.split, task)
        for row in df_rows.itertuples(index=False)
    ]
    rows = []
    with mp.Pool(processes=num_workers, initializer=_worker_init) as pool:
        for sample_id, (worker_arg, (history_len, event_list)) in enumerate(zip(
            worker_args,
            tqdm(pool.imap(process_row, worker_args, chunksize=32), total=len(worker_args)),
        )):
            pid, pred_time, label, split, task_ = worker_arg
            rows.append({
                "sample_id":       sample_id,
                "pass_idx":        0,
                "patient_id":      pid,
                "task":            task_,
                "split":           split,
                "prediction_time": pred_time,
                "label":           label,
                "history_len":     history_len,
                "n_events":        len(event_list),
                "events":          event_list,
            })
    return rows


def verify_label_stats(df_labels: pd.DataFrame, task: str):
    """Print stats and warn if they deviate from expected values."""
    expected   = TASK_2_EXPECTED_STATS[task]
    n_labels   = len(df_labels)
    n_patients = df_labels["patient_id"].nunique()
    prevalence = df_labels["value"].mean()

    print(f"  Labels:     {n_labels}  (expected {expected['n_labels']})")
    print(f"  Patients:   {n_patients}  (expected {expected['n_patients']})")
    print(f"  Prevalence: {prevalence:.4f}  (expected ~{expected['prevalence']:.3f})")

    if abs(n_labels - expected["n_labels"]) > 5:
        print(f"  WARNING: label count {n_labels} differs from expected {expected['n_labels']}")
    if abs(n_patients - expected["n_patients"]) > 5:
        print(f"  WARNING: patient count {n_patients} differs from expected {expected['n_patients']}")
    if abs(prevalence - expected["prevalence"]) > 0.01:
        print(f"  WARNING: prevalence {prevalence:.4f} differs from expected {expected['prevalence']:.3f}")

    non_2359 = df_labels[~df_labels["prediction_time"].dt.strftime("%H:%M").eq("23:59")]
    if len(non_2359) > 0:
        print(f"  WARNING: {len(non_2359)} rows not at 23:59 — unexpected.")
    else:
        print(f"  OK: all prediction times are at 23:59 as expected.")


if __name__ == "__main__":
    args = parse_args()
    os.makedirs(args.path_to_output_dir, exist_ok=True)

    # ------------------------------------------------------------------ #
    # Load shared data into module-level globals BEFORE spawning workers.
    # On Linux (fork), child processes inherit this memory via copy-on-write.
    # ------------------------------------------------------------------ #
    print("Loading splits...")
    df_splits = pd.read_csv(args.path_to_splits_csv)
    df_splits = df_splits.rename(columns={"omop_person_id": "patient_id"})

    print("Loading code descriptions from concept.csv...")
    _code_descriptions.update(load_code_descriptions(args.path_to_concept_csv))
    print(f"  Loaded {len(_code_descriptions):,} code descriptions.")

    print("Loading ehrshot.csv (this may take a moment)...")
    df_ehr = pd.read_csv(args.path_to_data_csv, low_memory=False)
    df_ehr["start"] = pd.to_datetime(df_ehr["start"])
    print(f"  Loaded {len(df_ehr):,} events for {df_ehr['patient_id'].nunique():,} patients.")

    print("Pre-grouping events by patient_id...")
    _ehr_by_patient.update({
        pid: group.reset_index(drop=True)
        for pid, group in df_ehr.groupby("patient_id")
    })
    del df_ehr
    print(f"  Grouped {len(_ehr_by_patient):,} patients.\n")

    _sample_prob   = args.event_sample_prob
    _sample_target = args.event_sample_target

    # Resolve per-split targets: per-split arg > total_event_target > None
    _split_targets = {
        split: getattr(args, f"{split}_target") or args.total_event_target
        for split in ("train", "val", "test")
    }
    _any_target = any(v is not None for v in _split_targets.values())

    # Build filename suffix encoding sampling parameters
    # e.g.  _p0.6_m512_ntrain1000_nval200_ntest200
    _sample_suffix = f"_p{_sample_prob}" if _sample_prob is not None else ""
    if _sample_target is not None:
        _sample_suffix += f"_m{_sample_target}"
    if _any_target:
        targets = _split_targets
        if len(set(v for v in targets.values() if v is not None)) == 1:
            # all splits share the same target — compact form
            _sample_suffix += f"_n{next(v for v in targets.values() if v is not None)}"
        else:
            for split, tgt in targets.items():
                if tgt is not None:
                    _sample_suffix += f"_n{split}{tgt}"

    print(f"Sampling config:")
    print(f"  event_sample_prob   = {_sample_prob}")
    print(f"  event_sample_target = {_sample_target}  (per-patient cap per pass)")
    for split, tgt in _split_targets.items():
        print(f"  {split}_target        = {tgt}  (per-class target; None = single pass)")

    # ------------------------------------------------------------------ #
    # Process each task
    # ------------------------------------------------------------------ #
    for task in args.tasks:
        disease_name = TASK_2_DISEASE_NAME[task]
        print(f"{'='*60}")
        print(f"Task: {task}  ({disease_name})")

        # 1. Load labels
        path_to_labels = os.path.join(args.path_to_labels_dir, task, "labeled_patients.csv")
        df_labels = pd.read_csv(path_to_labels)
        df_labels["prediction_time"] = pd.to_datetime(df_labels["prediction_time"])

        # 2. Verify stats
        verify_label_stats(df_labels, task)

        # 3. Apply prediction strategy
        df_labels_sorted = df_labels.sort_values(["patient_id", "prediction_time"])
        if args.prediction_strategy == "first":
            df_rows = df_labels_sorted.groupby("patient_id", as_index=False).first()
        elif args.prediction_strategy == "last":
            df_rows = df_labels_sorted.groupby("patient_id", as_index=False).last()
        else:  # all
            df_rows = df_labels_sorted

        print(f"\n  After applying strategy='{args.prediction_strategy}':")
        print(f"  Rows: {len(df_rows)},  Positive rate: {df_rows['value'].mean():.4f}")

        # 4. Attach split labels
        df_rows = df_rows.merge(df_splits, on="patient_id", how="left")
        print(f"  Split breakdown:\n{df_rows['split'].value_counts().to_string()}")

        # 5. Cap rows for debugging
        if args.max_rows is not None:
            df_rows = df_rows.head(args.max_rows)
            print(f"\n  Capped to {len(df_rows)} rows (--max_rows={args.max_rows}).")

        # 6. Sample events — stream each (split, class) chunk directly into the
        #    final parquet via ParquetWriter so peak RAM == one chunk at a time.
        stem     = f"{task}_{args.prediction_strategy}{_sample_suffix}"
        path_out = os.path.join(args.path_to_output_dir, f"{stem}.parquet")

        global_sample_id = 0
        total_rows       = 0
        pq_writer        = None   # opened lazily on first chunk (to infer schema)

        def _write_chunk(chunk: list, writer_ref: list) -> pq.ParquetWriter:
            """Convert chunk to Arrow table and append to the parquet file."""
            df_chunk = pd.DataFrame(chunk)
            table    = pa.Table.from_pandas(df_chunk, preserve_index=False)
            if writer_ref[0] is None:
                writer_ref[0] = pq.ParquetWriter(path_out, table.schema)
            writer_ref[0].write_table(table)
            return len(df_chunk)

        writer_ref = [None]   # mutable container so _write_chunk can update it

        if _any_target:
            for split in ("train", "val", "test"):
                tgt      = _split_targets[split]
                df_split = df_rows[df_rows["split"] == split]
                df_pos   = df_split[df_split["value"] == True]
                df_neg   = df_split[df_split["value"] == False]
                print(f"\n  [{split}] pos records: {len(df_pos):,}  |  neg records: {len(df_neg):,}")

                for label_name, df_class in (("pos", df_pos), ("neg", df_neg)):
                    if tgt is not None:
                        print(f"  [{split}/{label_name}] collecting {tgt:,} samples...")
                        chunk = collect_to_target(
                            df_class, task, tgt,
                            args.num_workers, label_name=f"{split}/{label_name}",
                        )
                    else:
                        print(f"  [{split}/{label_name}] single pass...")
                        chunk = run_single_pass(df_class, task, args.num_workers)

                    for r in chunk:
                        r["sample_id"] = global_sample_id
                        global_sample_id += 1

                    n = _write_chunk(chunk, writer_ref)
                    total_rows += n
                    print(f"  [{split}/{label_name}] {n:,} samples written")
                    del chunk
                    gc.collect()

        else:
            print(f"\n  Extracting samples with {args.num_workers} workers (single pass)...")
            chunk = run_single_pass(df_rows, task, args.num_workers)
            n = _write_chunk(chunk, writer_ref)
            total_rows += n
            del chunk
            gc.collect()

        if writer_ref[0] is not None:
            writer_ref[0].close()

        # 7. Print summary (read only metadata / small columns — no full reload)
        pf = pq.ParquetFile(path_out)
        df_meta = pf.read(columns=["split", "label"]).to_pandas()
        print(f"\n  Total samples: {total_rows:,}")
        print(f"  Label distribution:\n{df_meta.groupby(['split', 'label']).size().to_string()}")
        del df_meta
        print(f"  Saved -> {path_out}\n")

    print("Done.")
