#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import logging
import os
import time
from pathlib import Path
from typing import Any

from openai import OpenAI


logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)


def parse_args():
    p = argparse.ArgumentParser(
        description="Query an OpenAI-compatible API with EHR prompt JSONL files.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--input_path", required=True, help="JSONL generated by generate_llm_ehr_prompts.py")
    p.add_argument("--output_path", required=True, help="Output JSONL with model responses")
    p.add_argument("--model", default="doubao-seed-2.0-pro")
    p.add_argument("--base_url", default="https://ark.cn-beijing.volces.com/api/coding/v3", help="OpenAI-compatible API base URL")
    p.add_argument("--api_key", default="ark-afa46a5e-ccdb-4690-9d13-4564abb4b114-3ff97", help="API key; defaults to OPENAI_API_KEY")
    p.add_argument("--system_prompt", default="You are a careful clinical reasoning assistant.")
    p.add_argument("--temperature", type=float, default=0.0)
    p.add_argument("--top_p", type=float, default=1.0)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--timeout", type=float, default=600.0)
    p.add_argument("--max_retries", type=int, default=5)
    p.add_argument("--retry_sleep_seconds", type=float, default=5.0)
    p.add_argument("--resume", action="store_true", help="Skip rows already present in output_path")

    # Provider/model capability settings
    p.add_argument("--context_window_tokens", type=int, default=256_000)
    p.add_argument("--max_input_tokens", type=int, default=224_000)
    p.add_argument("--max_output_tokens", type=int, default=128_000)
    p.add_argument("--max_reasoning_tokens", type=int, default=128_000)

    # API style / compatibility knobs
    p.add_argument("--api_mode", choices=["responses", "chat_completions"], default="chat_completions")
    p.add_argument("--reasoning_effort", default=None, choices=[None, "low", "medium", "high"],
                   help="Optional reasoning effort for APIs/models that support it.")
    p.add_argument("--include_reasoning_config", action="store_true",
                   help="Attach a generic reasoning config block in extra body for compatible providers.")
    return p.parse_args()


def estimate_tokens_rough(text: str) -> int:
    # Simple heuristic for guarding obviously too-long prompts without tokenizer dependence.
    return max(1, len(text) // 4)


def load_existing_patient_ids(output_path: Path) -> set[int]:
    if not output_path.exists():
        return set()
    seen = set()
    with output_path.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                if "patient_id" in obj:
                    seen.add(int(obj["patient_id"]))
            except Exception:
                continue
    return seen


def build_client(args) -> OpenAI:
    api_key = args.api_key or os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("Missing API key. Pass --api_key or set OPENAI_API_KEY.")
    return OpenAI(
        api_key=api_key,
        base_url=args.base_url,
        timeout=args.timeout,
    )


def build_extra_body(args) -> dict[str, Any]:
    extra_body: dict[str, Any] = {}
    if args.include_reasoning_config:
        extra_body["reasoning"] = {"max_tokens": args.max_reasoning_tokens}
    return extra_body


def query_chat_completions(client: OpenAI, args, prompt: str) -> dict[str, Any]:
    request_kwargs: dict[str, Any] = {
        "model": args.model,
        "messages": [
            {"role": "system", "content": args.system_prompt},
            {"role": "user", "content": prompt},
        ],
        "temperature": args.temperature,
        "top_p": args.top_p,
        "seed": args.seed,
        "max_completion_tokens": args.max_output_tokens,
    }
    if args.reasoning_effort is not None:
        request_kwargs["reasoning_effort"] = args.reasoning_effort
    extra_body = build_extra_body(args)
    if extra_body:
        request_kwargs["extra_body"] = extra_body
    resp = client.chat.completions.create(**request_kwargs)
    choice = resp.choices[0]
    text = choice.message.content if choice.message else None
    return {
        "raw_response": resp.model_dump(),
        "text": text,
        "finish_reason": choice.finish_reason,
    }


def query_responses(client: OpenAI, args, prompt: str) -> dict[str, Any]:
    request_kwargs: dict[str, Any] = {
        "model": args.model,
        "input": [
            {"role": "system", "content": [{"type": "text", "text": args.system_prompt}]},
            {"role": "user", "content": [{"type": "text", "text": prompt}]},
        ],
        "max_output_tokens": args.max_output_tokens,
        "temperature": args.temperature,
        "top_p": args.top_p,
    }
    if args.reasoning_effort is not None:
        request_kwargs["reasoning"] = {"effort": args.reasoning_effort}
    extra_body = build_extra_body(args)
    if extra_body:
        request_kwargs["extra_body"] = extra_body
    resp = client.responses.create(**request_kwargs)
    text = getattr(resp, "output_text", None)
    return {
        "raw_response": resp.model_dump(),
        "text": text,
    }


def query_one(client: OpenAI, args, prompt: str) -> dict[str, Any]:
    if args.api_mode == "responses":
        return query_responses(client, args, prompt)
    return query_chat_completions(client, args, prompt)


def main():
    args = parse_args()
    input_path = Path(args.input_path)
    output_path = Path(args.output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    client = build_client(args)
    seen_patient_ids = load_existing_patient_ids(output_path) if args.resume else set()
    if seen_patient_ids:
        logger.info("Resume mode: found %d existing patient_ids in %s", len(seen_patient_ids), output_path)

    logger.info("Input: %s", input_path)
    logger.info("Output: %s", output_path)
    logger.info("Model: %s", args.model)
    logger.info("API mode: %s", args.api_mode)
    logger.info(
        "Context settings: context_window=%d max_input=%d max_output=%d max_reasoning=%d",
        args.context_window_tokens,
        args.max_input_tokens,
        args.max_output_tokens,
        args.max_reasoning_tokens,
    )

    num_total = 0
    num_written = 0
    num_skipped = 0

    with input_path.open() as fin, output_path.open("a") as fout:
        for line in fin:
            line = line.strip()
            if not line:
                continue
            num_total += 1
            obj = json.loads(line)
            patient_id = int(obj["patient_id"])
            if patient_id in seen_patient_ids:
                num_skipped += 1
                continue

            prompt = obj["prompt"]
            est_tokens = estimate_tokens_rough(prompt)
            if est_tokens > args.max_input_tokens:
                result = {
                    **obj,
                    "error": f"estimated_input_tokens_exceed_limit:{est_tokens}>{args.max_input_tokens}",
                    "estimated_input_tokens": est_tokens,
                }
                fout.write(json.dumps(result, ensure_ascii=False) + "\n")
                num_written += 1
                continue

            last_err = None
            response_payload = None
            for attempt in range(1, args.max_retries + 1):
                try:
                    response_payload = query_one(client, args, prompt)
                    break
                except Exception as e:
                    last_err = repr(e)
                    logger.warning(
                        "Request failed for patient_id=%s attempt=%d/%d: %s",
                        patient_id,
                        attempt,
                        args.max_retries,
                        last_err,
                    )
                    if attempt < args.max_retries:
                        time.sleep(args.retry_sleep_seconds)
            if response_payload is None:
                result = {
                    **obj,
                    "error": last_err or "unknown_error",
                    "estimated_input_tokens": est_tokens,
                }
            else:
                result = {
                    **obj,
                    "estimated_input_tokens": est_tokens,
                    "response_text": response_payload.get("text"),
                    "response_meta": {k: v for k, v in response_payload.items() if k != "text"},
                }
            fout.write(json.dumps(result, ensure_ascii=False) + "\n")
            fout.flush()
            num_written += 1

    logger.info(
        "Done. total=%d written=%d skipped=%d output=%s",
        num_total,
        num_written,
        num_skipped,
        output_path,
    )


if __name__ == "__main__":
    main()
